[package]
name = "known-folders"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.61"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_System_Com",
    "Win32_UI_Shell",
]
